/*
---
name: MooTools Rotating Element/Image 

description: Very simple but eloquent 3D rotating element script.

license: MIT-style

authors:
- Craig Fairhurst

requires:
- MooTools 1.6.0 Fx.Morph


provides: [Element, Fx.Morph]


*/